export const standardExercises = [
  {
    name: 'Barbell Back Squats',
    category: 'Legs',
    targetMuscle: 'Quadriceps, Glutes',
    secondaryMuscle: 'Hamstrings, Calves, Lower Back, Core',
    difficulty: 'Beginner',
    equipment: 'Barbell, Squat Rack',
    description: 'The king of lower body exercises. Builds full lower body strength, core stability, and functional athletic power.',
    instructions: '1. Position bar across upper back/traps, feet shoulder-width apart.\n2. Keep chest proud, core braced, and spine neutral.\n3. Inhale and hinge hips back, bending knees to lower until thighs are parallel to floor.\n4. Ensure knees track over toes without caving inward.\n5. Drive through mid-foot and heels to return to standing position.\n6. Exhale at the top and repeat with controlled cadence.',
    safetyInstructions: 'Do not let knees cave inwards. Avoid rounding the lower back (butt wink). Use a safety rack with catch bars set just below parallel.',
    defaultDuration: 60,
    defaultSets: 3,
    defaultRepetitions: 15,
    defaultRest: 45,
    animationType: 'animation',
    videoUrl: '',
    thumbnailUrl: 'https://images.unsplash.com/photo-1574680096145-d05b474e2155?w=500&auto=format&fit=crop&q=60',
    status: 'Active'
  },
  {
    name: 'Push-ups',
    category: 'Chest',
    targetMuscle: 'Pectoralis Major, Triceps',
    secondaryMuscle: 'Anterior Deltoids, Core, Serratus Anterior',
    difficulty: 'Beginner',
    equipment: 'No Equipment / Bodyweight',
    description: 'Fundamental horizontal pressing movement building upper body pressing strength, chest definition, and core endurance.',
    instructions: '1. Place hands slightly wider than shoulder-width, fingers pointing forward.\n2. Form a straight plank line from heels through glutes to head.\n3. Brace core and squeeze glutes.\n4. Lower body until chest is approximately 2 inches off the ground.\n5. Keep elbows at a 45-degree angle to torso.\n6. Push firmly into floor to return to top plank position.',
    safetyInstructions: 'Do not let lower back sag or hips pike up. Keep neck neutral by looking at floor 6 inches ahead.',
    defaultDuration: 45,
    defaultSets: 3,
    defaultRepetitions: 12,
    defaultRest: 30,
    animationType: 'animation',
    videoUrl: '',
    thumbnailUrl: 'https://images.unsplash.com/photo-1598971639058-fab3c3109a00?w=500&auto=format&fit=crop&q=60',
    status: 'Active'
  },
  {
    name: 'Barbell Bench Press',
    category: 'Chest',
    targetMuscle: 'Pectoralis Major',
    secondaryMuscle: 'Triceps Brachii, Anterior Deltoids',
    difficulty: 'Intermediate',
    equipment: 'Barbell, Flat Bench',
    description: 'Compound upper-body power movement maximizing chest hypertrophy and pushing strength.',
    instructions: '1. Lie flat on bench with eyes directly under bar, feet planted firmly on ground.\n2. Grip barbell slightly wider than shoulder-width with wrists straight.\n3. Unrack bar and hold over mid-chest with arms locked.\n4. Inhale and lower bar with control to touch lower sternum.\n5. Press bar upward and slightly back toward eye line while exhaling.',
    safetyInstructions: 'Always use collars/clamps and use a spotter when lifting heavy. Do not bounce the bar off your ribcage.',
    defaultDuration: 60,
    defaultSets: 4,
    defaultRepetitions: 10,
    defaultRest: 60,
    animationType: 'animation',
    videoUrl: '',
    thumbnailUrl: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=500&auto=format&fit=crop&q=60',
    status: 'Active'
  },
  {
    name: 'Pull-ups',
    category: 'Back',
    targetMuscle: 'Latissimus Dorsi',
    secondaryMuscle: 'Biceps Brachii, Rhomboids, Trapezius, Forearms',
    difficulty: 'Intermediate',
    equipment: 'Pull-up Bar',
    description: 'Supreme vertical pulling exercise for a wide V-taper back, powerful biceps, and grip strength.',
    instructions: '1. Grip pull-up bar with overhand grip (palms facing away), hands slightly wider than shoulders.\n2. Hang at full arm extension with shoulders engaged.\n3. Pull chest up toward the bar by driving elbows down and back.\n4. Continue pulling until chin clears the bar.\n5. Lower down smoothly with full control to starting hang.',
    safetyInstructions: 'Avoid swinging or kipping unless doing specialized crossfit training. Lower under control to protect shoulder labrum.',
    defaultDuration: 45,
    defaultSets: 3,
    defaultRepetitions: 8,
    defaultRest: 60,
    animationType: 'animation',
    videoUrl: '',
    thumbnailUrl: 'https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?w=500&auto=format&fit=crop&q=60',
    status: 'Active'
  },
  {
    name: 'Walking Dumbbell Lunges',
    category: 'Legs',
    targetMuscle: 'Quadriceps, Gluteus Maximus',
    secondaryMuscle: 'Hamstrings, Calves, Core',
    difficulty: 'Beginner',
    equipment: 'Dumbbells / Bodyweight',
    description: 'Dynamic unilateral leg builder improving balance, pelvic symmetry, glute development, and functional mobility.',
    instructions: '1. Stand tall holding dumbbells at your sides.\n2. Step forward with right leg and lower hips until both knees are bent at roughly 90 degrees.\n3. Back knee should hover just an inch above the floor.\n4. Push through front heel and step forward with opposite leg into the next lunge.\n5. Maintain upright posture throughout the walk.',
    safetyInstructions: 'Do not let front knee extend past toes excessively. Keep hips level and avoid trunk swaying.',
    defaultDuration: 60,
    defaultSets: 3,
    defaultRepetitions: 12,
    defaultRest: 30,
    animationType: 'animation',
    videoUrl: '',
    thumbnailUrl: 'https://images.unsplash.com/photo-1434682881908-b43d0467b798?w=500&auto=format&fit=crop&q=60',
    status: 'Active'
  },
  {
    name: 'Forearm Plank',
    category: 'Core',
    targetMuscle: 'Transverse Abdominis, Rectus Abdominis',
    secondaryMuscle: 'Obliques, Shoulders, Glutes',
    difficulty: 'Beginner',
    equipment: 'Yoga Mat',
    description: 'Isometric core stability foundation building 360-degree abdominal endurance and lower-back protection.',
    instructions: '1. Lie face down, rest weight on forearms directly beneath shoulders.\n2. Clasp hands or keep palms flat.\n3. Tuck toes and elevate body into a rigid plank from head to heels.\n4. Squeeze glutes, brace abs like anticipating a punch.\n5. Breathe rhythmically and hold position for assigned duration.',
    safetyInstructions: 'Do not let hips drop down towards floor or pike into the air. Keep neck aligned with spine.',
    defaultDuration: 45,
    defaultSets: 3,
    defaultRepetitions: 1,
    defaultRest: 30,
    animationType: 'animation',
    videoUrl: '',
    thumbnailUrl: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=500&auto=format&fit=crop&q=60',
    status: 'Active'
  },
  {
    name: 'Standing Dumbbell Overhead Press',
    category: 'Shoulders',
    targetMuscle: 'Anterior & Lateral Deltoids',
    secondaryMuscle: 'Triceps, Upper Chest, Core',
    difficulty: 'Intermediate',
    equipment: 'Dumbbells',
    description: 'Vertical pressing essential for 3D shoulder development, rotator cuff health, and core stability.',
    instructions: '1. Stand with feet hip-width apart, holding dumbbells at shoulder level with palms forward.\n2. Brace core and glutes to avoid hyperextending lumbar spine.\n3. Press weights straight overhead until arms are fully extended.\n4. Lower dumbbells smoothly under control back to shoulder height.',
    safetyInstructions: 'Do not arch lower back excessively. If lower back arches, switch to a staggered stance or seated position.',
    defaultDuration: 45,
    defaultSets: 3,
    defaultRepetitions: 10,
    defaultRest: 45,
    animationType: 'animation',
    videoUrl: '',
    thumbnailUrl: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=500&auto=format&fit=crop&q=60',
    status: 'Active'
  },
  {
    name: 'Dumbbell Bicep Curls',
    category: 'Arms',
    targetMuscle: 'Biceps Brachii',
    secondaryMuscle: 'Brachialis, Forearm Flexors',
    difficulty: 'Beginner',
    equipment: 'Dumbbells',
    description: 'Isolation arm builder creating bicep peak, arm thickness, and elbow flexor endurance.',
    instructions: '1. Stand tall holding dumbbells at sides, palms facing inward.\n2. Keeping upper arms pinned to sides, curl dumbbells up while supinating palms face-up.\n3. Squeeze biceps intensely at top contraction.\n4. Lower dumbbells slowly over 2-3 seconds back to starting position.',
    safetyInstructions: 'Do not swing hips or lean backwards to create momentum. Maintain strict elbow positioning.',
    defaultDuration: 45,
    defaultSets: 3,
    defaultRepetitions: 12,
    defaultRest: 30,
    animationType: 'animation',
    videoUrl: '',
    thumbnailUrl: 'https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?w=500&auto=format&fit=crop&q=60',
    status: 'Active'
  },
  {
    name: 'Barbell Romanian Deadlift (RDL)',
    category: 'Back',
    targetMuscle: 'Hamstrings, Gluteus Maximus',
    secondaryMuscle: 'Erector Spinae, Lats, Trapezius',
    difficulty: 'Intermediate',
    equipment: 'Barbell',
    description: 'Premier hip hinge pattern strengthening the posterior chain, improving posture and hamstring flexibility.',
    instructions: '1. Stand holding barbell with overhand grip at thighs, feet hip-width apart.\n2. Unlock knees slightly (soft bend) and keep them stationary.\n3. Hinge at hips, pushing glutes backward while keeping barbell skimming down your shins.\n4. Lower until feeling a deep hamstring stretch (mid-shin height).\n5. Drive hips forward and squeeze glutes to return upright.',
    safetyInstructions: 'Maintain a flat back at all times. Do not let barbell drift away from your legs.',
    defaultDuration: 60,
    defaultSets: 4,
    defaultRepetitions: 10,
    defaultRest: 60,
    animationType: 'animation',
    videoUrl: '',
    thumbnailUrl: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=500&auto=format&fit=crop&q=60',
    status: 'Active'
  },
  {
    name: 'Russian Twists',
    category: 'Core',
    targetMuscle: 'Internal & External Obliques',
    secondaryMuscle: 'Rectus Abdominis, Hip Flexors',
    difficulty: 'Beginner',
    equipment: 'Medicine Ball / Bodyweight',
    description: 'Rotational core powerhouse developing waist definition, rotational torque, and dynamic torso stability.',
    instructions: '1. Sit on floor, bend knees, and elevate feet slightly off ground into a V-sit.\n2. Lean torso back to 45-degree angle.\n3. Clasp hands or hold a weight in front of chest.\n4. Rotate torso fully to right side, tapping weight near floor.\n5. Rotate smoothly to left side and repeat in controlled rhythm.',
    safetyInstructions: 'Rotate through upper spine and torso, not just swinging arms. Keep chest elevated to protect lumbar spine.',
    defaultDuration: 45,
    defaultSets: 3,
    defaultRepetitions: 20,
    defaultRest: 30,
    animationType: 'animation',
    videoUrl: '',
    thumbnailUrl: 'https://images.unsplash.com/photo-1518611012118-696072aa579a?w=500&auto=format&fit=crop&q=60',
    status: 'Active'
  }
];
